<table><?php
    if (!$this->firstRow) {
?>
<tr height="20px">&nbsp;</tr>
<?php
    }
?>

<tr>
    <td width="20px">&nbsp;</td>

<?php
foreach ($this->row as $item) {
    if (!is_null($item)) {
?>
    <td width="100px"><?php echo $this->thumbnailCover($item['coverSrc'], $item['exploreUri'], $item['title']) ?></td>
    <td width="20px">&nbsp;</td>
<?php
    } else {
?>
    <td width="100px">&nbsp;</td>
    <td width="20px">&nbsp;</td>
<?php
    }
}
?>
</tr>
</table>