<?php
$pageData = $this->pageData;
?>
<script type="text/javascript">
    $(document).ready(function(){

            $('#page_container').pajinate({
					num_page_links_to_display : 13,
					items_per_page : 3,
                                        nav_label_first: '<?php echo $this->translate("#First") ?>',
                                        nav_label_prev: '<?php echo $this->translate("#Prev") ?>',
                                        nav_label_last: '<?php echo $this->translate("#Last") ?>',
                                        nav_label_next: '<?php echo $this->translate("#Next") ?>',
                                        nav_label_info: '<?php echo $this->translate("#Showing {0}-{1} of {2} results") ?>'
				});

        $('.page_link').on('click', function(e) {
            e.preventDefault();
            jQuery('html, body').animate({scrollTop: top}, 800);

        return false;
        });
    });
</script>

<!-- conteudo -->
<div id="conteudo" style="width:580px;">

<h1><?php echo $this->translate("#Editions") ?></h1>

<?php
    if ((isset($pageData['themeData'])) && ($pageData['themeData']['term'])) {
        $themeData = $pageData['themeData'];
?>

<h2><?php echo sprintf($this->translate("#Editions with theme '%s'", $themeData['term'])) ?></h2>


<?php
    }

?>
<?php
    if ((isset($pageData['typeData']['term'])) && ($pageData['typeData']['term'])) {
        $typeData = $pageData['typeData'];
?>

<h2><?php echo $typeData['term'] ?></h2>


<?php
    }

?>
<?php
    if ((isset($pageData['characterData'])) && ($pageData['characterData']['term'])) {
        $characterData = $pageData['characterData'];
?>

<h2><?php echo sprintf($this->translate("#Editions with character '%s'", $characterData['term'])) ?></h2>


<?php
    }

?>
<?php
    if ((isset($pageData['serieData'])) && ($pageData['serieData']['title'])) {
        $serieData = $pageData['serieData'];
?>

<h2><?php echo sprintf($this->translate("#Editions of serie '%s'", $serieData['title'])) ?></h2>


<?php
    }

?>
<?php
    if ((is_array($pageData['editionsModel'])) && (count($pageData['editionsModel']))){

?>

<!--<table id="livros" width="580px">-->
<div id="page_container">
<div id="livros" style="width:580px">
<ul class="content">
    <?php echo $this->editionsRows($pageData['editionsModel']) ?>
</ul>
</div>
<!-- paginacao -->
<div class="page_navigation"></div>
<!--<div class="info_text"></div>-->
<!-- /paginacao -->
</div>
<!--</table>-->
<?php
    } else {

?>
<h3>
    <?php echo $this->translate("#There are no works with this criteria."); ?>
</h3>
<?php
    }

?>

</div>
<!-- /conteudo -->
