<!-- box livros -->
<h2><?php echo $this->translate("#Categories") ?></h2>

<!-- item de repeticao -->
<div class="item_box">
<h3 class="categorias"><a href=""><?php echo $this->translate("#In the press") ?></a></h3>
</div>
<!-- /item de repeticao -->

<!-- item de repeticao -->
<div class="item_box">
<h3 class="categorias"><a href="">Leitura</a></h3>
</div>
<!-- /item de repeticao -->

<!-- item de repeticao -->
<div class="item_box">
<h3 class="categorias"><a href="">Professor</a></h3>
</div>
<!-- /item de repeticao -->

<!-- item de repeticao -->
<div class="item_box" style="border:none;margin-bottom:0;">
<h3 class="categorias" style="margin-bottom:0;"><a href="">Agenda</a></h3>
</div>
<!-- /item de repeticao -->

<!-- /box livros -->