<!-- box featured book -->
<h2><img src="img/icone_livro.png" alt="Livro em destaque" align="absmiddle" /> Livro em destaque</h2>

<div><a href="/livro/poemas-que-escolhi-para-as-criancas" title="Poemas Que Escolhi Para As Crianças"><img src="img/poemas_home.png" alt="Poemas Que Escolhi Para As Crianças" /></a></div>

<a href="/livro/poemas-que-escolhi-para-as-criancas" title="Poemas Que Escolhi Para As Crianças" class="link_box">Poemas Que Escolhi Para As Crianças</a>

<!-- /box  featured book -->
