<div id="rodape" class="clearfix">
<p class="float_left align_left">&copy;2013 Ruth Rocha. Todos os direitos reservados. Ilustra&ccedil;&otilde;es de Mariana Massarani.	</p>
<!--<p class="float_right align_right">
	<a href="" title="Facebook"><img src="/img/icone_facebook.png" alt="Facebook" /></a>
    <a href="" title="Twitter"><img src="/img/icone_twitter.png" alt="Twitter" /></a>
    <a href="" title="Youtube"><img src="/img/icone_youtube.png" alt="Youtube" /></a>
</p>-->
</div>