<?php echo $this->panel() ?>
<div id="topo" class="clearfix">

<!-- logo -->
<div id="logo">
	<a href="/home" title="Home"><img src="/img/logo.png" alt="Ruth Rocha" /></a>
</div>
<!-- /logo -->

<!-- menu -->
<ul id="menu">
	<li><a href="/livros" title="Livros" id="menu_livros">Livros</a></li>
    <li><a href="/novidades" title="Novidades" id="menu_novidades">Novidades</a></li>
    <li><a href="/biografia" title="Biografia" id="menu_biografia">Biografia</a></li>
    <li><a href="/contato" title="Contato" id="menu_contato">Contato</a></li>
</ul>
<!-- /menu -->

</div>