<?php
$pageData = $this->pageData;
?>
<!-- conteudo -->
<div id="conteudo">
    <h1><?php echo $pageData['title'] ?></h1>
    <h2><a href="<?php echo $pageData['typeListLink']?>"><?php echo $pageData['typeLabel']?></a></h3> <a href="/admin/work/change-type/?id=<?php echo $pageData['id'] ?>"><?php echo $this->translate('#(change type)')?></a></p>

    <h3><?php echo $this->translate('#Description')?></h2>
    <p><?php echo $pageData['description']?></p>
    <p><a href="/admin/work/change-description/?id=<?php echo $pageData['id'] ?>"><?php echo $this->translate("#(change description)") ?></a></p>

    <h3><?php echo $this->translate('#Summary')?></h2>
    <p><?php echo $pageData['summary']?></p>
    <p> <a href="/admin/work/change-summary/?id=<?php echo $pageData['id'] ?>"><?php echo $this->translate("#(change summary)") ?></a></p>

    <h3><?php echo $this->translate('#Theme')?></h2>
    <p><?php echo $pageData['themeModel']['term']?></p>
    <p><a href="/admin/work/change-theme/?id=<?php echo $pageData['id'] ?>"><?php echo $this->translate("#Change theme") ?></a></p>

    <h3><?php echo $this->translate('#Characters')?></h2>
    <?php if ((is_array($pageData['characters']))&&(count($pageData['characters']))) { ?>
    <?php echo $this->charactersLoop($pageData['characters']) ?>
    <?php } ?>
    <p><a href="/admin/work/create-character/?id=<?php echo $pageData['id'] ?>"><?php echo $this->translate("#Add character") ?></a></p>

    <h3><?php echo $this->translate('#Prizes')?></h2>
    <?php if ((is_array($pageData['prizes']))&&(count($pageData['prizes']))) { ?>
    <?php echo $this->prizesLoop($pageData['prizes']) ?>
    <?php } ?>
    <p><a href="/admin/prize/create/?work=<?php echo $pageData['id'] ?>"><?php echo $this->translate("#Add prize") ?></a></p>

    <input type="hidden" name="id" value="<?php echo $pageData['id'] ?>" id="id">

    <h3><?php echo $this->translate('#Editions.admin')?></h2>
    <?php if ((is_array($pageData['editions']))&&(count($pageData['editions']))) { ?>
    <?php echo $this->editionsLoop($pageData['editions']) ?>
    <?php } ?>
    <hr>
    <a href="/admin/work/remove/?id=<?php echo $pageData['id'] ?>"><?php echo $this->translate('#(remove this work!)')?></a></p>
</div>
<!-- /conteudo -->

<script>

  $("#new-theme-click").click(function(){
      var workId = $('#id').val();

      $.ajax({
          type: 'get',
          data: 'work=' + workId,
          url:'/admin/theme/create/',
          success: function(successReturn){
          $('#new-theme-div').html(successReturn);
          }
      })
      $("#new-theme-div").show("slow");
  });
  $("#hide-new-theme").click(function(){
      $("#new-theme-div").hide("slow");
  });


</script>