<?php
  $pageData = $this->pageData;
?>
        <div id="conteudo">
          <h1><?php echo $this->translate("#Remove work") ?></h1>
        </div>
          <p class="clear_both">
              <?php echo sprintf($this->translate("#Do you confirm removal of character %s from %s? This CAN'T be undone."), "<strong>{$pageData['term']}</strong>", $pageData['title']) ?>
          </p>
        <?php echo $this->form; ?>
