<div id="conteudo">

<h1>Biografia</h1>

  <p>Ruth Rocha nasceu em 1931 na cidade de São Paulo. Filha dos cariocas Álvaro de Faria Machado, médico, e Esther de Sampaio Machado, tem quatro irmãos, Rilda, Álvaro, Eliana e Alexandre. Teve uma infância alegre e repleta de livros e gibis. O bairro de Vila Mariana, onde morava, tinha nessa época muitas chácaras por onde Ruth passava, a caminho da escola - estudava no Colégio Bandeirantes. Mais tarde, terminou o Ensino Médio no Colégio Rio Branco. </p>
  <p>É graduada em Sociologia e Política pela Universidade de São Paulo e pós-graduada em Orientação Educacional pela Pontifícia Universidade Católica de São Paulo. Casada com Eduardo Rocha, tem uma filha, Mariana e dois netos, Miguel e Pedro. </p>
  <p>Durante 15 anos (de 1956 a 1972) foi orientadora educacional do Colégio Rio Branco, onde pôde conviver com os conflitos e as difíceis vivências infantis e com as mudanças do seu tempo. A liberação da mulher, as questões afetivas e de auto-estima foram sedimentando-se em sua formação.</p>
  <p>Começou a escrever em 1967, para a revista Claudia, artigos sobre educação. Participou da criação da revista Recreio, da Editora Abril, onde teve suas primeiras histórias publicadas a partir de 1969. “Romeu e Julieta”, “Meu Amigo Ventinho”, “Catapimba e Sua Turma”, “O Dono da Bola”, “Teresinha e Gabriela” estão entre seus primeiros textos de ficção. Ainda na Abril, foi editora, redatora e diretora da Divisão de Infanto-Juvenis. </p>
  <p>Publicou seu primeiro livro, “Palavras Muitas Palavras”, em 1976, e desde então já teve mais de 130 títulos publicados, entre livros de ficção, didáticos, paradidáticos e um dicionário. As histórias de Ruth Rocha estão espalhadas pelo mundo, traduzidas em mais de 25 idiomas.</p>
  <p>Monteiro Lobato foi sua grande influência. Em sua obra, essa influência se traduz pelo seu interesse nos problemas sociais e políticos, na sua tendência ao humor e nas suas posições feministas.</p>
  <p>Seu livro de forte conteúdo crítico, “Uma História de Rabos Presos”, foi lançado em 1989 no Congresso Nacional em Brasília, com a presença de grande número de parlamentares. Em 1988 e 1990 lançou na sede da Organização das Nações Unidas em Nova York seus livros “Declaração Universal dos Direitos Humanos” para crianças e “Azul e Lindo – Planeta Terra Nossa Casa”.</p>
  <p>Participou durante seis anos do programa de televisão Gazeta Meio-Dia como membro fixo da mesa de debates. </p>
  <p>Em 1998 foi condecorada pelo presidente Fernando Henrique Cardoso com a Comenda da Ordem do Mérito Cultural do Ministério da Cultura.</p>
  <p>Ganhou os mais importantes prêmios brasileiros destinados à literatura infantil da Fundação Nacional do Livro Infantil e Juvenil, da Câmara Brasileira do Livro, cinco Prêmios “Jabuti”, da Associação Paulista de Críticos de Arte e da Academia Brasileira de Letras, Prêmio João de Barro, da Prefeitura de Belo Horizonte, entre outros.</p>
  <p>Seu livro mais conhecido é “Marcelo, Marmelo, Martelo”, que já vendeu mais de 1 milhão de cópias.</p>
  <p>Em 2002 ganhou o prêmio Moinho Santista de Literatura Infantil, da Fundação Bunge. Também nesse ano foi escolhida como membro do PEN CLUB – Associação Mundial de Escritores no Rio de Janeiro. </p>
  <p>Atualmente é membro do Conselho Curador da Fundação Padre Anchieta.</p>
</div>
