<div id="conteudo">

<script type="text/javascript">
    $(document).ready(function(){

            $('#page_container').pajinate({
					num_page_links_to_display : 10,
					items_per_page : 1,
                                        nav_label_first: '<?php echo $this->translate("#First") ?>',
                                        nav_label_prev: '<?php echo $this->translate("#Prev") ?>',
                                        nav_label_last: '<?php echo $this->translate("#Last") ?>',
                                        nav_label_next: '<?php echo $this->translate("#Next") ?>',
                                        nav_label_info: '<?php echo $this->translate("#Showing {0}-{1} of {2} results") ?>'
				});

        $('.page_link').on('click', function(e) {
            e.preventDefault();
            jQuery('html, body').animate({scrollTop: top}, 800);

        return false;
        });
    });
</script>



<h1>Biografia</h1>
<div id="paginas_biografia">
<div id="page_container">
<ul class="content">
    <li>
        <p><em>De como a menina que devorava livros virou a escritora que aprendeu a voar. </em></p>
        <p>Quando Ruth Rocha sorri o mundo parece sorrir à sua volta. Na verdade são muitos mundos que se iluminam diante do seu eterno olhar de menina. A começar pelo que ela viu se transformar em mais de 80 anos de vida, metade deles dedicados a escrever histórias que marcam a vida de milhões de crianças e jovens. </p>
        <p>Uma das maiores escritoras da literatura infanto-juvenil brasileira, Ruth nasceu em 2 de março de 1931, em uma São Paulo muito diferente onde cada bairro parecia uma cidade do interior. Na Vila Mariana onde cresceu haviam grandes chácaras, com muitas árvores, carregadas de flores e frutos, quintais e caminhos de terra que foram cenário para as suas brincadeiras e aventuras de infância. </p>
        <p>A segunda filha do Doutor Álvaro e de dona Esther, ouviu da mãe as primeiras histórias contadas como tradição de família ou lidas em livros de contos clássicos e de Monteiro Lobato. </p>
        <p>O mundo da literatura se abriu de vez com Reinações de Narizinho e Emília conquistou sua identificação imediata, na irreverência e no bom humor que definem seu jeito de ser e na incorporação do imaginário à realidade que influenciou sua arte de escrever. </p>
        <p>No caldeirão de histórias que iam se misturando e fertilizando a memória da futura escritora estão os causos e contos narrados pelo avô baiano. Mestre em fundir a tradição de histórias folclóricas dos Irmãos Grimm, Perrault, Andersen e As mil e uma noites com o universo popular brasileiro, principalmente do interior da Bahia, com suas bonecas de piche e macacos que perdiam o rabo, Vovô Ioiô cantava e inventava músicas , fazia versos e anedotas e viajava por lugares improváveis como Caixaprego e a Ladeira do Escorrega. </p>
    </li>
    <li>
        <p>Na casa da família de cinco irmãos havia uma biblioteca onde Ruth se encantou com um livro que não tinha nada de infantil mas que a despertou para a sonoridade e rima dos  versos dos cantores nordestinos. Ainda adolescente descobriu a Biblioteca Circulante no centro da cidade. Decidiu ler todos os livros do mundo, começando por ali, prateleira por prateleira. E se aborrecia quando o próximo da fila havia sido emprestado. </p>
        <p>Nada lhe escapava, dos romances aos relatos de viagem passando pela poesia. Seus preferidos eram Fernando Pessoa, Manuel Bandeira, Machado de Assis, mais tarde Guimarães Rosa e de novo e sempre Monteiro Lobato. Mas foi Eça de Queiroz com A cidade e as serras lido para um trabalho de ginásio aos 13 anos que a fez se apaixonar de vez pela literatura. </p>
        <p>Formada em Ciências Políticas e Sociais pela Escola de Sociologia e Política de São Paulo foi aluna do autor de Raízes do Brasil, o mestre Sérgio Buarque de Holanda que a guiou numa viagem de estudo pelas ruas de Ouro Preto. Na faculdade, conheceu e se apaixonou pelo industrial Eduardo Rocha com quem se casou e viveu por 56 anos até o falecimento dele em 2012.  Juntos tiveram a filha Mariana, inspiração das suas primeiras histórias. </p>
        <p>Ruth começou a trabalhar na biblioteca do Colégio Rio Branco e logo em seguida se tornou Orientadora Educacional do mesmo colégio, entre 1957 e 1972. Foi durante essa época que passou a escrever sobre educação para a revista Cláudia, a convite do amigo Carlos Alberto Fernandes. </p>
        <p>Sua visão moderna sobre o tema e o estilo próprio e direto, chamaram a atenção de outra amiga, Sonia Robato, que  dirigia a Recreio, revista de histórias e brincadeiras para o público infantil. </p>
        <p>Sonia fez um convite que se tornou um desafio para Ruth. Em tom de brincadeira ela trancou a amiga numa sala dizendo que só saísse de lá com uma história pronta. </p>
    </li>
    <li>
        <p>Foi então que se lembrou da pergunta feita pela filha Mariana que gostava de ouvir a mãe inventando histórias e queria saber por que preto era pobre. Se para a socióloga a resposta renderia uma tese, para a futura escritora foi o ponto de partida para Romeu e Julieta, o encontro de duas borboletas de reinos e cores diferentes que souberam derrubar preconceitos para se tornarem amigas. </p>
        <p>Seria a primeira de uma série de histórias sempre originais, divertidas e que faziam pensar publicadas na Recreio. A revista que Ruth depois veio a dirigir se tornou um marco,  lançando a partir de 1969 toda uma  geração de autores e ilustradores que começaram a escrever um novo e importante capítulo da literatura infantil no Brasil.  </p>
        <p>Mas ainda levaria alguns anos para Ruth ter um livro publicado. Antes disso, iniciou uma nova carreira: a partir de 1973 se tornou editora de livros, revistas e fascículos passando a coordenar o departamento de publicações infanto-juvenis da Editora Abril. </p>
        <p><em>Palavras</em>, muitas palavras  veio a público pela primeira vez em 1976. Brincando com o alfabeto, Ruth cria versos e rimas que remetem às modinhas, parlendas e trava-linguas com a sonoridade dos contos de tradição oral da sua infância. Estavam lá desde o começo o jeito  inovador de se dirigir ao leitor e as influências presentes em toda sua obra.</p>
        <p>A literatura infantil no Brasil nunca mais foi a mesma. Ruth Rocha entrou para um universo que ajudou a revolucionar, elevou a qualidade dos livros publicados e ensinou o mercado a tratar com respeito seus pequenos leitores. Em um tempo em que criança mal tinha direito de dirigir a palavra a um adulto mostrou o quanto elas são dotadas de inteligência e senso crítico. </p>
        <p>Tudo isso em meio a um dos períodos mais difíceis da história do país. Em plena ditadura, sua obra ousava respirar liberdade e conduzia o leitor a enxergar a realidade sem perder a fantasia. Com a ousadia e a graça de uma criança. Sempre com grande inventividade e seu estilo inconfundível. </p>
    </li>
    <li>
        <p>Assim surgiram <em>Marcelo, Marmelo, Martelo</em> – o menino que questionava os significados e inventava novas palavras, seu maior best-seller e um dos maiores sucessos editoriais do país com 25 edições e 10 milhões de exemplares vendidos - ; <em>O reizinho mandão</em> – incluído na “Lista de Honra” do prêmio internacional Hans Christian Anderson - ; <em>Nicolau tinha uma idéia</em> e logo depois <em>A menina que aprendeu a voar</em>; <em>Dois idiotas sentados cada qual no seu barril</em>; <em>O rei que não sabia de nada</em> e <em>Uma história de rabos presos</em>. </p>
        <p> Em mais de 40 anos dedicados à literatura, Ruth Rocha conta com mais 130 títulos publicados, 35 deles no exterior onde foram traduzidos para 25 idiomas. Somam-se também as mais de 60 traduções de obras infanto-juvenis além de livros didáticos, como <em>Escrever e Criar é só começar</em> que escreveu com Ana Flora e a coleção <em>O Homem e a Comunicação</em> com Otávio Roth. Uma obra reconhecida com 8 Jabutis da Câmera Brasileira de Letras. </p>
        <p>Ruth recebeu prêmios da Academia Brasileira de Letras, da Associação Paulista dos Críticos de Arte e da Fundação Nacional do Livro Infantil e Juvenil. Ganhou também o prêmio Santista da Fundação Bunge, o prêmio de Cultura da Fundação Conrad Wessel e a Comenda da Ordem do Mérito Cultural. </p>
        <p>A escritora que sempre defendeu os direitos da criança foi parar na ONU, sua versão para a <em>Declaração Universal dos Direitos Humanos</em> teve lançamento na sede da Organização das Nações Unidas em Nova York, em 1988. </p>
        <p>A menina que um dia decidiu ler todos os livros da biblioteca hoje tem várias bibliotecas com o seu nome, no interior de São Paulo, no Rio e em Brasília. A primeira delas foi inaugurada em 1989 em Sapopemba, na Zona Leste da capital paulista. Homenagem à autora que ampliou o alcance da literatura ajudando a formar novos leitores por todo país.</p>
        <p>Em 2008, Ruth Rocha foi eleita membro da Academia Paulista de Letras. </p>
    </li>
    <li>
        <p>O colorido dos quintais da sua infância, os jogos e brincadeiras da calçada, os meninos e meninos da vizinhança hoje habitam a série <em>A turma da nossa rua</em>. Ali estão personagens que se misturam à infância da filha como nas <em>Aventuras de Alvinho</em>; <em>O piquenique do Catapimba</em>; <em>A Cinderela das Bonecas</em>. E agora também dos seus netos. Com Miguel e Pedro os pequenos ganharam a <em>Coleção Comecinho</em> que a vovó Ruth escreveu e o vovô Eduardo ilustrou. </p>
        <p>De geração em geração, para todas as idades, em quantidade e qualidade, a obra de Ruth é tão generosa quanto sua autora. Com a adaptação de clássicos como a <em>Ilíada</em> e a <em>Odisséia</em> abriu espaço para o talento de um ilustrador que estava sempre por perto acompanhando o nascimento de cada livro. Eduardo Rocha o companheiro da vida toda fez sua estréia na nova profissão aos 60 anos e recebeu o prêmio máximo da ABL. </p>
        <p>Entre a irreverência e a independência, acrescentando  imaginação à realidade, com poesia e bom humor, invertendo mitos e fantasias, ousadas e até malcriadas mas sempre bem contadas. Suas histórias ensinam a criança a se questionar e faz o adulto enxergar e ouvir o que elas pensam como em <em>O menino que quase virou cachorro</em> e <em>A menina que aprendeu a voar</em>.  Provocando a curiosidade e despertando o pensamento crítico Ruth nunca deixa de lado a esperança e o otimismo. Muitas histórias não tem um final fechado, terminam com um convite à ação e à reflexão ou simplesmente com uma provocação, <em>a quem quiser que conte outra</em>. </p>
        <p>Assim toda a obra parece sorrir junto com sua autora. </p>
        <p>E quem ouviu suas histórias na infância hoje se diverte ao contá-las e recontá-las para seus filhos. Afinal, ler e reler Ruth Rocha é descobrir em cada conto e poema, um novo capítulo de uma grande história de amor à literatura e aos livros. </p>
        <p>Mas ao escrever as brincadeiras, confusões e aventuras de Beto, Marcelo, Nicolau, Gabriela, Caloca, Mariana e tantos outros o que Ruth revela o tempo todo é o seu  profundo amor, respeito e cumplicidade por todas as crianças. Em histórias que escreve com o mesmo carinho e generosidade dos versos com que conclui um de seus poemas, <em>toda criança do mundo cabe no meu coração</em>. </p>
    </li>
</ul>
<!-- paginacao -->
<div class="page_navigation"></div>
</div>

</div>
</div>
