<?php
$pageData = $this->pageData;
?>
<div id="conteudo">

<h1><?php echo $pageData['title'] ?></h1>

<!-- detalhes -->
<div class="detalhe">
<?php echo $this->translate('#Theme:') ?> <a href="<?php echo $this->translate('/theme/') ?><?php echo $pageData['themeUri'] ?>"><?php echo $pageData['themeLabel'] ?></a> <span>|</span>
<?php if ((isset($pageData['typeLabel'])) && ($pageData['typeLabel'])) { ?>
<?php echo $this->translate('#Age:') ?> <a href=""><?php echo $pageData['typeLabel'] ?></a>
<?php } ?>
</div>
<!-- /detalhes -->

<!--<p><img src="/img/marcacao_livro_detalhe.jpg" class="float_left" /><strong>&Aacute;tica, 2000</strong></p>-->
<p><a href="<?php echo $pageData['mediumImageUri']?>"><?php $this->exploreCover($pageData['mediumImageUri']) ?></a></p>
<p><?php echo $pageData['description']?></p>

<p>
<?php if ((isset($pageData['serieName'])) && ($pageData['serieName'])) { ?>
<?php echo $this->translate("#Serie:")?> <a href="/colecao/<?php echo $pageData['serieUri']?>"><?php echo  $pageData['serieName'] ?></a><br />
<?php } ?>
<?php if ((isset($pageData['illustrator'])) && ($pageData['illustrator'])) { ?>
<?php echo $pageData['illustrator']?><br />
<?php } ?>
<?php if ((isset($pageData['coverDesigner'])) && ($pageData['coverDesigner'])) { ?>
<?php echo $pageData['coverDesigner']?><br />
<?php } ?>
<?php if ((isset($pageData['editorName'])) && ($pageData['editorName'])) { ?>
<?php echo $pageData['editorName']?><br />
<?php } ?>
<?php if ((isset($pageData['isbn'])) && ($pageData['isbn'])) { ?>
<?php echo $pageData['isbn']?><br />
<?php } ?>
<?php if ((isset($pageData['pages'])) && ($pageData['pages'])) { ?>
<?php echo $pageData['pages']?><br />
<?php } ?>

</p>

<!--
<form>
<input type="submit" value="Comprar online" />
</form>
-->

<?php $this->editionSerie($pageData['edition'], $pageData['editionMapper'], $pageData['serieName'], $pageData['serieUri'], $pageData['sameSerieData']) ?>
</div>