<?php
  $controller = Zend_Controller_Front::getInstance();
  $request = $controller->getRequest();
  $controller->setParam('outerModule', $request->getModuleName());
  $params = $controller->getParams();
?>

<!-- header -->
<?php echo $this->action('header', 'include', 'includes') ?>
<!-- /header -->

<!-- container -->
<div id="container" class="clearfix">

<!-- conteudo -->
<?php echo $this->layout()->content; ?>
<!-- /conteudo -->

<!-- lateral -->
<div id="lateral">
<div class="box2 clearfix box_home"><?php echo $this->action('featured-character', 'include', 'includes') ?></div>
</div>
<!-- /lateral -->




</div>
<!-- /container -->
<!-- rodape -->
<br /><br /><br />
<?php echo $this->action('footer-home', 'include', 'includes') ?>
<!-- /rodape -->
