<?php
  $controller = Zend_Controller_Front::getInstance();
  $request = $controller->getRequest();
  $controller->setParam('outerModule', $request->getModuleName());
  $params = $controller->getParams();
?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script type="text/javascript" src="/js/jquery.pajinate.js"></script>

<?php
    $controllerName =  $controller->getRequest()->getControllerName();
    $actionName = $controller->getRequest()->getActionName();
    if (($controllerName == 'edition') && ($actionName == 'explore')) {

        echo $this->headScript()->prependFile($this->baseUrl('js/shadowbox/shadowbox.js'));
        echo $this->headLink()->prependStylesheet($this->baseUrl('css/shadowbox.css'));
?>
<script type="text/javascript">
Shadowbox.init();
</script>
<?php
    }

?>

<!-- header -->
<?php echo $this->action('header', 'include', 'includes') ?>
<!-- /header -->

<!-- container -->
<div id="container" class="clearfix livros">

<!-- breadcrumb -->
<div id="breadcrumb_livros">
<?php echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render(); ?>
</div>
<!-- /breadcrumb -->

<!-- conteudo -->
<?php echo $this->layout()->content; ?>
<!-- /conteudo -->

<!-- lateral -->
<div id="lateral">
<div class="box clearfix"><?php echo $this->action('filter', 'include', 'includes') ?></div>
<div class="box clearfix"><?php echo $this->action('search', 'include', 'includes') ?></div>
</div>
<!-- /lateral -->
</div>
<!-- /container -->
<!-- rodape -->
<br /><br /><br />
<div title="" id="rodape_container" class="clearfix" style="background:url(/img/personagens/livros.png) bottom center no-repeat">
<?php echo $this->action('footer', 'include', 'includes') ?>
<?php echo $this->panel() ?>
</div>
<!-- /rodape -->

