<?php
  $controller = Zend_Controller_Front::getInstance();
  $request = $controller->getRequest();
  $controller->setParam('outerModule', $request->getModuleName());
  $params = $controller->getParams();
?>

<!-- header -->
<?php echo $this->action('header', 'include', 'includes') ?>
<!-- /header -->

<!-- container -->
<div id="container" class="clearfix">


<!-- destaque -->
<div id="destaque">

<div id="banner-fade">

<ul class="bjqs">
  <li><a href="/livros"><img src="img/banner01.jpg" title="Amigos da bola"></a></li>
  <li><a href="/biografia"><img src="img/banner02.jpg" title="Biblioteca de São Paulo recebe Ruth Rocha"></a></li>
  <li><a href="/novidades"><img src="img/banner03.jpg" title="Almanaque Ruth Rocha"></a></li>
</ul>

</div>

<script class="secret-source">
jQuery(document).ready(function($) {

  $('#banner-fade').bjqs({
    height      : 430,
    width       : 990,
    responsive  : true
  });

});
</script>

</div>
<!-- /destaque -->

<!-- conteudo -->
<?php echo $this->layout()->content; ?>
<!-- /conteudo -->

<!-- lateral -->
<div id="lateral">
<div class="box2 clearfix box_home"><?php echo $this->action('featured-character', 'include', 'includes') ?></div>
</div>
<!-- /lateral -->




</div>
<!-- /container -->
<!-- rodape -->
<br /><br /><br />
<?php echo $this->action('footer-home', 'include', 'includes') ?>
<!-- /rodape -->
