<?php
  $controller = Zend_Controller_Front::getInstance();
  $request = $controller->getRequest();
  $controller->setParam('outerModule', $request->getModuleName());
  $params = $controller->getParams();
?>


<!-- header -->
<?php echo $this->action('header-login', 'include', 'includes') ?>
<!-- /header -->
<!-- container -->
<div id="container" class="clearfix admin">
<!-- conteudo -->
<?php echo $this->layout()->content; ?>
<!-- /conteudo -->
</div>
<!-- /container -->
<!-- rodape -->
<?php echo $this->action('footer', 'include', 'includes') ?>
<!-- /rodape -->