<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="content-language" content="pt-br" />
<meta http-equiv="Cache-Control" content="no-cache" />
<meta http-equiv="Pragma" content="no-cache" />
<meta name="googlebot" content="noarchive" />
<meta name="robots" content="index,follow" />
<meta name="googlebot" content="ALL" />
<?php echo $this->headMeta()->appendName('keywords', $this->keywords); ?>
<meta name="description" content="Site Oficial da Ruth Rocha" />
<meta name="author" content="Além Disso" />
<meta name="google" content="notranslate" />
<link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon" />
<link rel="icon" href="/img/favicon.ico" type="image/x-icon" />
